### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by SaeedPoureshghi** [EngRobot33/ZED#3]
Adding API endpoints to use in platforms like react-native or reactJs to implement more performance front.

**Comment by HaamedKhosravii** [comment]
Yes, you are right, and the project does not have any APIs. Data is managed in HTML pages using Jinja. If it becomes necessary to add APIs, the current frontend pages will not be used. In fact, I am considering adding APIs, and I would be very happy if someone uses frontend frameworks to develop the appearance of the project.
