### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by parsarezaee** [EngRobot33/ZED#4]
Hi Hamed,
I noticed this project isn't Dockerized yet. I believe Dockerizing it could be useful for deployments and stuff.

**Comment by HaamedKhosravii** [comment]
Hello Parsa,
Yes, the project has not been dockerized yet and it is actually necessary to dockerize it. Can you dockerize it?

**Comment by parsarezaee** [comment]
@EngRobot33 
Thanks for confirming!  I'm glad we agree Dockerizing the project would be beneficial. Do you have any specific preferences or considerations for the Dockerfile structure or deployment process? Once I have it working, I'll submit a pull request for your review.

**Comment by HaamedKhosravii** [comment]
@parsarezaee 
In local stage the database is still SQLite but later in both local and deployment stage, We should turn into PostgreSQL. In first steps, just consider SQLite for database (I don't know If it's necessary a db service for SQLite in docker compose file). Also It should be a Redis server for handling requests.
The main service port is 8000, SQLite has not any specific port and Redis is 6379.

**Comment by HaamedKhosravii** [comment]
I have to inform you the project has been dockerized by @ArmanTaheriGhaleTaki. So I close this issue and I hope you collaborate on other parts of the project, Dear @parsarezaee.
